docs_dir: 'docs'
site_dir: 'static'
site_name: Pisound Micro Documentation
site_author: UAB VILNIAUS BLOKAS
use_directory_urls: true
theme:
  name: 'material'
  favicon: 'favicon.ico'
  logo: 'images/logo.svg'
  palette:
    primary: 'white'
    accent: 'white'
  custom_dir: 'blokas-docs-theme'
  features:
    - navigation.expand
    - navigation.instant
    - navigation.footer
    - content.tabs.link
site_url: https://blokas.io/pisound-micro/docs/
extra:
  ads:
    pisound: false
    patchboxos: false
    midihub: false
    modep: false
  #discourse: 'https://community.blokas.io/'
  disqus: 'fake'
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/BlokasLabs"
    - icon: "fontawesome/brands/x-twitter"
      link: "https://twitter.com/blokaslabs"
    - icon: "fontawesome/brands/facebook"
      link: "https://www.facebook.com/blokaslabs/"
repo_name: 'pisound-micro-docs'
repo_url: 'https://github.com/BlokasLabs/pisound-micro-docs/'
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - markdown.extensions.md_in_html
  - toc:
      permalink: '#'
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: False
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - footnotes:
      PLACE_MARKER: '///Footnotes Go Here///'

copyright: '&copy; 2025 VILNIAUS BLOKAS UAB'

nav:
  - Pisound Micro: index.md
  - Getting Started: getting-started.md
  - Audio Connections: audio-connections.md
  - ALSA Mixer: alsa-mixer.md
  - Detailed Specs: detailed-specs.md
  - Pisound Micro Mapper: pisound-micro-mapper.md
  - Sysfs Interface: sysfs-interface.md
  - libpisoundmicro:
      - Overview: libpisoundmicro/overview.md
      - C API: libpisoundmicro/c.md
      - C++ API: libpisoundmicro/cpp.md
      - Python API: libpisoundmicro/python-api.md
  - Sysfs GPIO: sysfs-gpio.md
  - gpiod & libpgiod: gpiod-libgpiod.md
  - License: license.md

plugins:
  - search
  - mkdoxy:
      projects:
        libpisoundmicro:
          src-dirs: libpisoundmicro
          template-dir: mkdoxy_templates
          doxy-cfg:
            PROJECT_NAME: libpisoundmicro
      save-api: md_tmp_files
  - mkdocstrings:
      custom_templates: blokas-docs-theme/templates/mkdocstrings
      handlers:
        python:
          options:
            show_source: false
            docstring_style: sphinx
            show_root_heading: false
            show_root_toc_entry: false
            unwrap_annotated: false
            heading_level: 3
            show_bases: true
